"""Tests against real-trace fixtures generated from production SDKs.

Each fixture is generated by `scripts/generate_fixtures.py` (e.g.
`uv run python scripts/generate_fixtures.py langgraph`) and committed
to the repo. If a fixture is missing the corresponding test class is
skipped rather than failing — this lets contributors who haven't
regenerated fixtures still run the suite.

Synthetic fixtures (under `tests/fixtures/synthetic/`) verify the spec;
these tests verify that the spec survives contact with what real SDKs
actually emit.

Each SDK's tests are grouped in their own class with their own skip
mark, so a missing LangGraph fixture doesn't affect ADK tests and
vice versa.
"""

from __future__ import annotations

from pathlib import Path

import pytest

import otela

REAL_FIXTURES_DIR = Path(__file__).parent / "fixtures" / "real"
LANGGRAPH_FIXTURE = REAL_FIXTURES_DIR / "langgraph_research_agent.json"
ADK_FIXTURE = REAL_FIXTURES_DIR / "adk_research_agent.json"


# ---------------------------------------------------------------------------
# LangGraph (OpenInference)
# ---------------------------------------------------------------------------


@pytest.mark.skipif(
    not LANGGRAPH_FIXTURE.exists(),
    reason=(
        "Real LangGraph fixture not generated. Run "
        "`uv run python scripts/generate_fixtures.py langgraph` to create it."
    ),
)
class TestLangGraphFixture:
    @pytest.fixture
    def tables(self):
        return otela.load(LANGGRAPH_FIXTURE)

    def test_loads_without_errors(self, tables):
        assert tables["spans"].num_rows > 0

    def test_one_trace(self, tables):
        """The fixture is a single agent invocation, so one trace."""
        assert tables["traces"].num_rows == 1

    def test_convention_detected(self, tables):
        """LangChain instrumentation emits OpenInference attributes; nothing
        in this fixture should fall back to UNKNOWN convention."""
        conventions = set(tables["spans"].column("convention").to_pylist())
        assert "openinference" in conventions
        assert "unknown" not in conventions, (
            f"Some spans were not classified into a known convention: {conventions}"
        )

    def test_extracts_at_least_one_llm_span(self, tables):
        kinds = set(tables["spans"].column("kind").to_pylist())
        assert "LLM" in kinds

    def test_extracts_tool_span(self, tables):
        """The `get_weather` tool call should produce a TOOL span."""
        spans = tables["spans"].to_pandas()
        tool_spans = spans[spans["kind"] == "TOOL"]
        assert len(tool_spans) >= 1, "expected at least one TOOL span from get_weather"

    def test_model_name_extracted(self, tables):
        spans = tables["spans"].to_pandas()
        llm_spans = spans[spans["kind"] == "LLM"]
        assert llm_spans["model_name"].notna().any(), (
            "no LLM span carried a model_name — extraction may have regressed"
        )

    def test_token_counts_extracted(self, tables):
        spans = tables["spans"].to_pandas()
        llm_spans = spans[spans["kind"] == "LLM"]
        assert llm_spans["input_tokens"].notna().any(), (
            "no LLM span carried input_tokens — token extraction may have regressed"
        )
        assert llm_spans["output_tokens"].notna().any()

    def test_messages_captured(self, tables):
        """OpenInference encodes messages as indexed attributes; some LLM span
        should produce at least one message row."""
        msgs = tables["messages"]
        assert msgs.num_rows > 0, "no messages extracted from LangChain LLM spans"

    def test_no_orphaned_spans(self, tables):
        """Every span (except the root) should have a parent_span_id present
        in the spans table."""
        spans = tables["spans"].to_pandas()
        span_ids = set(spans["span_id"])
        parents_referenced = set(spans["parent_span_id"].dropna()) - {None}
        missing = parents_referenced - span_ids
        assert not missing, f"spans reference parents not in the trace: {missing}"

    def test_trace_status_consistent(self, tables):
        """The trace-level status rollup should match what we see on spans."""
        spans_status = set(tables["spans"].column("status_code").to_pylist())
        trace_status = tables["traces"].column("status").to_pylist()[0]
        if "ERROR" in spans_status:
            assert trace_status == "ERROR"
        elif "OK" in spans_status:
            assert trace_status in {"OK", "ERROR"}

    def test_service_name_propagated(self, tables):
        services = set(tables["spans"].column("service_name").to_pylist())
        assert services == {"langgraph-research-agent"}


# ---------------------------------------------------------------------------
# Google ADK (OTel GenAI semconv via LiteLLM bridge)
# ---------------------------------------------------------------------------


@pytest.mark.skipif(
    not ADK_FIXTURE.exists(),
    reason=(
        "Real ADK fixture not generated. Run "
        "`uv run python scripts/generate_fixtures.py adk` to create it."
    ),
)
class TestADKFixture:
    @pytest.fixture
    def tables(self):
        return otela.load(ADK_FIXTURE)

    def test_loads_without_errors(self, tables):
        assert tables["spans"].num_rows > 0

    def test_one_trace(self, tables):
        assert tables["traces"].num_rows == 1

    def test_convention_is_otel_genai(self, tables):
        """ADK emits gen_ai.* attributes natively, so most spans should be
        classified as `otel_genai`. Internal container spans (e.g. ADK's
        top-level `invocation`) carry no GenAI markers and correctly land
        as `unknown`; those are fine. The point of this test is that the
        SDK-level convention is detected at all."""
        conventions = set(tables["spans"].column("convention").to_pylist())
        assert "otel_genai" in conventions, (
            f"expected at least one otel_genai-classified span, got conventions={conventions}"
        )

    def test_extracts_llm_and_tool_spans(self, tables):
        kinds = set(tables["spans"].column("kind").to_pylist())
        assert "LLM" in kinds, f"expected an LLM kind span; got kinds={kinds}"
        assert "TOOL" in kinds, f"expected a TOOL kind span; got kinds={kinds}"

    def test_agent_name_extracted(self, tables):
        """ADK populates `gen_ai.agent.name` on `invoke_agent` spans."""
        agents = set(tables["spans"].column("agent_name").to_pylist()) - {None}
        assert agents, "no span carried an agent_name; gen_ai.agent.name extraction may have regressed"

    def test_tool_name_extracted(self, tables):
        """ADK populates `gen_ai.tool.name` on `execute_tool` spans."""
        tools = set(tables["spans"].column("tool_name").to_pylist()) - {None}
        assert tools, "no span carried a tool_name; gen_ai.tool.name extraction may have regressed"

    def test_messages_extracted_from_span_events(self, tables):
        """Critical: ADK emits messages as span events (not indexed attrs).
        Verifies the events-based path works on real SDK output."""
        msgs = tables["messages"]
        assert msgs.num_rows > 0, (
            "no messages extracted from ADK trace; the span-events path may have regressed"
        )

    def test_messages_have_directions(self, tables):
        """Both inputs and outputs should be classified."""
        directions = set(tables["messages"].column("direction").to_pylist()) - {None}
        # We expect at least one input message; outputs may or may not be present
        # depending on whether the model emits gen_ai.choice or gen_ai.assistant.message.
        assert "input" in directions, f"no input-direction messages; got {directions}"

    def test_no_orphaned_spans(self, tables):
        spans = tables["spans"].to_pandas()
        span_ids = set(spans["span_id"])
        parents_referenced = set(spans["parent_span_id"].dropna()) - {None}
        missing = parents_referenced - span_ids
        assert not missing, f"spans reference parents not in the trace: {missing}"

    def test_service_name_propagated(self, tables):
        services = set(tables["spans"].column("service_name").to_pylist())
        assert services == {"adk-weather-agent"}
